version: 2

sources:
  - name: source
    description: "This is the source data for the dbt tutorial"
    database: dbt_tutorial_dev
    tables:
      - name: fact_sales
        description: "This table contains sales data"
      - name: dim_customer
        description: "This table contains customer data"
      - name: dim_product
        description: "This table contains product data"
      - name: dim_date
        description: "This table contains date data"
      - name: dim_store
        description: "This table contains store data"
      - name: fact_returns
        description: "This table contains returns data"




