ankit_dbt_youtube:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-235fcbc3-e513.cloud.databricks.com
      http_path: /sql/1.0/warehouses/7096e344e7ee4db1
      schema: default
      threads: 1
      token: 
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: dbc-235fcbc3-e513.cloud.databricks.com
      http_path: /sql/1.0/warehouses/7096e344e7ee4db1
      schema: default
      threads: 1
      token: 
      type: databricks 
  target: dev
